CREATE TABLE `news`.`news` (`ID` BIGINT NOT NULL AUTO_INCREMENT, `DATE` DATE, `BRIEF_CONTENT` VARCHAR(255), `CONTENT` LONGTEXT, `TITLE` VARCHAR(255), `AUTHOR_ID` BIGINT NOT NULL, PRIMARY KEY (`ID`));
CREATE TABLE `news`.`category` (`ID` BIGINT NOT NULL AUTO_INCREMENT, `NAME` VARCHAR(45), PRIMARY KEY (`ID`));
CREATE TABLE `news`.`news_category` (`NEWS_ID` BIGINT NOT NULL,`CATEGORY_ID` BIGINT NOT NULL, PRIMARY KEY (`NEWS_ID`, `CATEGORY_ID`));
CREATE TABLE `news`.`user` (`ID` BIGINT NOT NULL AUTO_INCREMENT,`FIRST_NAME` VARCHAR(45),`LAST_NAME` VARCHAR(45),`ROLE` VARCHAR(45), `LOGIN` VARCHAR(45), `PASSWORD` VARCHAR(45), `EMAIL` VARCHAR(45), PRIMARY KEY (`ID`));

ALTER TABLE `news`.`news` ADD CONSTRAINT `USER_FK` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `news`.`user` (`ID`);
ALTER TABLE `news`.`news_category` ADD CONSTRAINT `CATEGORY_FK` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `news`.`category` (`ID`);
ALTER TABLE `news`.`news_category` ADD CONSTRAINT `NEWS_FK` FOREIGN KEY (`NEWS_ID`) REFERENCES `news`.`news` (`ID`);
